# Generated by Django 3.2.8 on 2021-11-25 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211118_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='num_reviews',
            new_name='numReviews',
        ),
    ]
